controllers:
    resource: ../src/Controller/
    type: attribute

index:
   path: /
   controller: App\Controller\HomeController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

home:
    path: /home
    controller: App\Controller\HomeController::index
